# Generated by Django 5.2.1 on 2025-07-30 13:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('operateur_main', 'Opérateur manuel'), ('operateur_machine', 'Opérateur machine'), ('superviseur', 'Superviseur'), ('technicien', 'Technicien'), ('controle_qualite', 'Contrôle Qualité'), ('autre', 'Autre')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ordre', models.CharField(max_length=50, unique=True)),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('quantite_terminee', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix unitaire en devise locale', max_digits=10)),
                ('code_produit', models.CharField(max_length=50, unique=True)),
                ('nom_produit', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('siege_avant', 'Sièges avant'), ('siege_arriere', 'Sièges arrière'), ('garniture_laterale', 'Garniture latérale')], max_length=50)),
                ('statut', models.CharField(choices=[('en_production', 'En production'), ('fini', 'Fini'), ('stocke', 'Stocké')], default='en_production', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperationProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('decoupe', 'Découpe'), ('couture', 'Couture'), ('assemblage', 'Assemblage'), ('controle_qualite', 'Contrôle qualité'), ('autre', 'Autre')], max_length=30)),
                ('quantite_demandee', models.PositiveIntegerField(default=0)),
                ('quantite_produite', models.PositiveIntegerField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('employes', models.ManyToManyField(to='dashboard.employe')),
                ('ordre_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ordreproduction')),
            ],
        ),
        migrations.AddField(
            model_name='ordreproduction',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit')),
            ],
        ),
    ]
