# Generated by Django 5.2 on 2025-07-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordreproduction',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True),
        ),
    ]
