# Generated by Django 5.2.1 on 2025-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ordreproduction_date_fin_reelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('en_production', 'En production'), ('discontinue', 'Discontinué'), ('stocke', 'Stocké')], default='en_production', max_length=20),
        ),
    ]
