# Generated by Django 5.2.1 on 2025-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_stock_emplacement_alter_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(choices=[('magasin', 'Magasin'), ('entrepot', 'Entrepôt'), ('expedition', 'Expédition')], default='magasin', max_length=20),
        ),
    ]
