# Generated by Django 5.2.1 on 2025-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('production', 'Responsable Production'), ('stock', 'Responsable Stock'), ('qualite', 'Contrôleur Qualité'), ('technicien', 'Technicien')], default='admin', max_length=20),
        ),
    ]
